name: Wendy Prudencio 
logo: "images/B0DB81F8-2300-438A-9993-53F87A418728.jpg"
description: Class Assignment
  Week 1
  <br><br>
  GES 687 Course
  <br><br>
  <a href="www.linkedin.com/in/wprudencio">View My LinkedIn Profile</a> 
  

