title: Wendy Prudencio 
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > Class Assignment 
  Week 1
  <br><br>
 Literally testing this because it is harder than it seems.
  <br><br>
  <a href="www.linkedin.com/in/wprudencio">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
