title: Wendy Prudencio 
logo: "images/84260388-6FE0-4F4F-9DC9-8F42AD7F2D5E_1_201_a.jpeg" W: 533px H:533px
description: Class Assignment
  Week 1
  <br><br>
 Literally testing this because it is harder than it seems.
  <br><br>
  <a href="www.linkedin.com/in/wprudencio">View My LinkedIn Profile</a> 
  

