Name: Wendy Prudencio 
Logo: "images/B0DB81F8-2300-438A-9993-53F87A418728-2.jpg"
Description: Class Assignment
  Week 1
  <br><br>
 Literally testing this because it is harder than it seems.
  <br><br>
  <a href="www.linkedin.com/in/wprudencio">View My LinkedIn Profile</a> 
  

